#!/bin/bash
export AUDIOFORMAT='audio/x-raw, format=S16LE, layout=interleaved, rate=48000, channels=2'
(echo -en "audio feed ctr isaudio 1\n";gst-launch-1.0 -v audiotestsrc wave=12 is-live=true ! $AUDIOFORMAT ! fdsink fd=3 sync=true 3>&1 1>&2) | nc 127.0.0.1 9999
