#!/bin/bash
ID=`whoami`;
SCRIPTSDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
HOMEDIR=`eval echo ~$ID`;
UUID=`cat $HOMEDIR/logs/setup.log | tail -n 1`;
logfileGST="$HOMEDIR/logs/setup.$UUID/GST.log"
logfileSM="$HOMEDIR/logs/setup.$UUID/SM.log"
logfileGE="$HOMEDIR/logs/setup.$UUID/GE.log"
LOGDIR="$HOMEDIR/logs/setup.$UUID/"

cd $HOMEDIR
date
echo $UUID
echo $logfileSM

anbox session-manager --single-window --window-size=800,480 > $logfileSM 2>&1 &

(
date
while (( "`xwininfo -root -tree|grep anbox|sed "s/ /\n/g"|grep -v "^$"|wc -l`" == "0" )); do sleep 1; done
while true; do
    echo "Start OsmAnd begin"
    anbox launch --package=net.osmand --component=net.osmand.plus.activities.MapActivity
    if [[ "$?" == "0" ]]; then
	echo "Start OsmAnd end"
	break;
    fi
    sleep 3;
done
) > $LOGDIR/osmand_launch.log 2>&1 &

(
cd $SCRIPTSDIR/../build/AAServer/
date
while (( "`xwininfo -root -tree|grep anbox|sed "s/ /\n/g"|grep -v "^$"|wc -l`" == "0" )); do sleep 1; done
while true; do
    sudo chmod 777 socket
    export GST_PLUGIN_PATH=$SCRIPTSDIR/../build/AAVideoSink/
    gst-launch-1.0 ximagesrc show-pointer=false use-damage=false xname="Anbox - Android in a Box" ! videoconvert ! video/x-raw,width=800,height=480,pixel-aspect-ratio=1/1,framerate=30/1,format=I420 ! aavideosink socketName=socket
    sleep 3;
done
) > $logfileGST 2>&1 &

(
cd $SCRIPTSDIR/../build/GetEvents/
date
while (( "`xwininfo -root -tree|grep anbox|sed "s/ /\n/g"|grep -v "^$"|wc -l`" == "0" )); do sleep 1; done
while true; do
    sudo chmod 777 socket
    ./GetEvents ../AAServer/socket "Anbox - Android in a Box"
    sleep 3;
done
) > $logfileGE 2>&1 &
