#!/bin/bash
SCRIPTSDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. $SCRIPTSDIR/id
. $SCRIPTSDIR/common

echo $UUID

modprobe libcomposite

# max and default size for socket messages = 2MB (may need to be increased in case of higher resolution)
sysctl net.core.wmem_max=2097152
sysctl net.core.wmem_default=2097152

(
    export HOME=$HOMEDIR
    export SNOWMIX=/usr/lib/Snowmix-0.5.1.1/
    cd $HOMEDIR/snowmix/
    snowmix base.ini
) > $LOGDIR/snowmix.log 2>&1 < /dev/zero  &

(
while true; do
    lxc-attach -P $HOMEDIR/anbox-data/containers/ -n default ip r a default via 192.168.250.1
    if [[ "$?" == "0" ]]; then
	break;
    fi
    sleep 10;
done
) > $LOGDIR/attach.log 2>&1 &

(
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/`id -u $ID`/bus
while IFS= read -r line
do
    echo "$line"
    dbus-send --session --dest=org.anbox --type=method_call --print-reply /org/anbox org.anbox.Gps.PushSentence "string:$line"
done < <(gpspipe -r|stdbuf -i0 -o0 -e0 grep "\$GP")
) > $LOGDIR/gpspush.log 2>&1 &

(
while true; do
    x0vncserver -passwordfile $HOMEDIR/.vnc/passwd -display :0
    sleep 10;
done
) > $LOGDIR/X0.log 2>&1 &

devMode=`gpioget gpiochip0 62`; #connect pin1 and pin7 together
if [[ "$devMode" != "0" ]]; then
    echo "Development mode is on ('$devMode')";
    exit;
else
    echo "Development mode is off ('$devMode')";
fi

(
cd $SCRIPTSDIR/../build/AAServer/
i=0;
while true; do
    date;
    rm -f socket
    ./AAServer --dumpfile=$LOGDIR/dump.pcap.$i;
    sleep 1;
    ((i++));
done
) > $LOGDIR/Server.log 2>&1 &

(
cd $SCRIPTSDIR/../build/AAClient/
while true; do
    sleep 1;
    date;
    ./AAClient ../AAServer/socket;
done
) > $LOGDIR/Client.log 2>&1 &

(
while true; do
    sleep 1;
    sync;
done
)
